"""
Event-model interface and GR4H wrappers.

The Monte Carlo machinery never touches GR4H directly -- it talks to
:class:`EventModel`.  Two concrete wrappers are provided:

* :class:`GR4HEventEngine` -- :class:`pyfloodrisk.gr4h.GR4H`, the package's
  own numba implementation, hot-started from a sampled state vector.  This
  is the default: it is the same model code the calibration and the
  continuous run use, so the state distribution the events are started from
  is internally consistent with the model that consumes it.
* :class:`CallableEngine` -- wraps any Python callable with the signature
  ``f(rain, pet, state) -> discharge`` so you can plug in your own code.

Units: rainfall and PET in mm per timestep, discharge returned in m3/s.

State vector
------------
Engines are hot-started from a dict, as produced by
:meth:`pyfloodrisk.dffa.states.InitialStateSampler.to_state_dicts`::

    {"prod_store": mm, "rout_store": mm, "uh1": array, "uh2": array}

``uh1``/``uh2`` hold the water in transit through the unit hydrographs.  Note
that the *convention* for those arrays is the engine's own -- GR4H splits the
routed depth 0.9/0.1 between UH1 and UH2 at the point of use, and another
implementation may well split it on entry -- so a state table must be
generated by the same engine that consumes it
(:func:`pyfloodrisk.dffa.workflow.continuous_state_table` does this for
:class:`GR4HEventEngine`).
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Callable, Mapping, Sequence

import numpy as np

from ..gr4h.GR4H_model import GR4H

__all__ = ["EventModel", "CallableEngine", "GR4HEventEngine",
           "mm_per_step_to_cumecs"]


def mm_per_step_to_cumecs(q_mm: np.ndarray, area_km2: float, dt_hours: float) -> np.ndarray:
    """mm per timestep -> m3/s for a catchment of ``area_km2``.

    1 mm over 1 km2 is 1000 m3, so 1 mm/h over A km2 is ``A/3.6`` m3/s.
    """
    return np.asarray(q_mm, float) * area_km2 / (3.6 * dt_hours)


class EventModel(ABC):
    """Interface the Monte Carlo driver expects."""

    dt_hours: float = 1.0
    area_km2: float = 1.0

    @abstractmethod
    def run_event(self, rain: np.ndarray, pet: np.ndarray, state: dict) -> np.ndarray:
        """Discharge series in m3/s for one event."""

    def run_batch(self, events: Sequence[tuple[np.ndarray, np.ndarray, dict]]
                  ) -> list[np.ndarray]:
        """Run a batch.  Override for a faster/parallel implementation."""
        return [self.run_event(r, e, s) for r, e, s in events]

    # convenience -----------------------------------------------------------
    def peak(self, rain, pet, state) -> float:
        return float(np.max(self.run_event(rain, pet, state)))


@dataclass
class CallableEngine(EventModel):
    """Wrap your own GR4H implementation.

    ``fn(rain_mm, pet_mm, state) -> q`` where ``q`` is either mm per timestep
    (``returns="mm"``) or m3/s (``returns="cumecs"``).
    """

    fn: Callable[[np.ndarray, np.ndarray, dict], np.ndarray]
    area_km2: float = 1.0
    dt_hours: float = 1.0
    returns: str = "mm"

    def run_event(self, rain, pet, state):
        q = np.asarray(self.fn(rain, pet, state), float)
        if self.returns == "mm":
            return mm_per_step_to_cumecs(q, self.area_km2, self.dt_hours)
        return q


class GR4HEventEngine(EventModel):
    """:class:`pyfloodrisk.gr4h.GR4H` hot-started from a sampled state vector.

    Because this is the same model code as the calibration and the
    continuous run, the sampled state vector means the same thing to the
    event as it did to the run it was drawn from -- which is the whole
    premise of replacing the RORB sampled initial loss with a sampled model
    state.  Anything else, including a second GR4H implementation, has to
    come in through :class:`CallableEngine` along with a state table
    generated by that same implementation.

    Parameters
    ----------
    params : mapping or sequence
        GR4H parameters, either ``{"x1": ..., "x2": ..., "x3": ..., "x4": ...}``
        (extra keys such as ``ps0``/``rs0`` are ignored -- the initial
        condition comes from the sampled state) or the sequence
        ``[x1, x2, x3, x4]``.
    area_km2 : float
        Catchment area, used to convert mm/timestep to m3/s.
    dt_hours : float, optional
        Model timestep.  GR4H is an hourly model -- its percolation
        coefficient and unit-hydrograph exponent are the hourly values -- so
        anything other than 1.0 means you have rescaled the parameters
        yourself, and is warned about once.

    Notes
    -----
    :attr:`n_uh1` and :attr:`n_uh2` give the unit-hydrograph memory lengths
    implied by x4.  A sampled state whose UH arrays are a different length is
    zero-padded or truncated to match, so a state table generated with a
    different x4 will be silently misinterpreted: generate the state table
    with the same parameter set you run the events with.
    """

    def __init__(self, params, area_km2: float, dt_hours: float = 1.0):
        self.params = _gr4h_params(params)
        self.area_km2 = float(area_km2)
        self.dt_hours = float(dt_hours)
        if abs(self.dt_hours - 1.0) > 1e-9:
            import warnings
            warnings.warn(
                "GR4H is an hourly model (percolation coefficient 21/4 and UH "
                f"exponent 1.25 are the hourly values); running at dt_hours="
                f"{self.dt_hours} assumes you have rescaled the parameters",
                stacklevel=2)
        self._model = GR4H(area=self.area_km2, params=dict(self.params))

    def __repr__(self):
        p = self.params
        return (f"GR4HEventEngine(area_km2={self.area_km2:.2f}, "
                f"x1={p['x1']:.1f}, x2={p['x2']:.3f}, x3={p['x3']:.1f}, "
                f"x4={p['x4']:.2f})")

    @property
    def n_uh1(self) -> int:
        return self._model.n_uh1

    @property
    def n_uh2(self) -> int:
        return self._model.n_uh2

    def state_lengths(self) -> tuple[int, int]:
        """UH memory lengths ``(n_uh1, n_uh2)`` this engine expects."""
        return self.n_uh1, self.n_uh2

    def initial_state(self, prod_frac: float = 0.3, rout_frac: float = 0.5) -> dict:
        """A cold state, for smoke tests and sensitivity checks."""
        return self._model.initial_state(prod_frac, rout_frac)

    def run_event(self, rain, pet, state):
        out = self._model.run_from_state(rain, pet, state)
        return mm_per_step_to_cumecs(out["qt"], self.area_km2, self.dt_hours)


def _gr4h_params(params) -> dict:
    """Normalise GR4H parameters to ``{"x1", "x2", "x3", "x4"}``."""
    keys = ("x1", "x2", "x3", "x4")
    if isinstance(params, Mapping):
        missing = [k for k in keys if k not in params]
        if missing:
            raise ValueError(f"GR4H parameters missing {missing}")
        return {k: float(params[k]) for k in keys}
    values = np.asarray(params, float).ravel()
    if values.size != 4:
        raise ValueError("GR4H takes four parameters X1..X4")
    return dict(zip(keys, (float(v) for v in values)))
